name: Build and Deploy to ECR

on:
  workflow_dispatch: # This enables the "Run workflow" button
  push:
    branches: [ main ]
    paths:
      - 'webfiles/**'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}

permissions:
  id-token: write       # Required for requesting the OIDC JWT
  contents: read        # Required for actions/checkout
  pull-requests: write  # Required for plan comments
  issues: write

jobs:
  build-and-push:
    name: docker-ecr
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Authenticate to AWS via OIDC
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Checkout the repository to the runner
        uses: actions/checkout@v6.0.2

      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity

      - name: Debug OIDC context
        run: |
          echo "Role ARN: $AWS_ROLE_ARN"
          echo "Region: $AWS_REGION"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push frontend image to Amazon ECR
        id: containerImage
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          cd webfiles
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: ECR Status Check
        if: steps.containerImage.outcome == 'failure'
        run: exit 1
